### ISSUE TITLE
Please add pointer-events none

### ISSUE THREAD

**Issue by achavazza** [jkeyes/baseline#5]
Please add pointer-events:none; to the baseline overlay
it would improve and it will be easier to inspect and work with the bookmarklet

**Comment by bolatovumar** [comment]
I agree with this.

@hesselbom's [pull request](https://github.com/jkeyes/baseline/pull/4) seems to resolve this issue. I tested his fork and everything works as you would expect. Seem like it would be a good idea to merge it into master.

**Comment by jkeyes** [comment]
:+1: I'll do that.

**Comment by bolatovumar** [comment]
@jkeyes thanks!

**Comment by bolatovumar** [comment]
Resolved by https://github.com/jkeyes/baseline/commit/e5930c3646c75ce9d9fe1e31acf2117507b4c194
Issue can be closed now.

**Comment by jkeyes** [comment]
I'll close when I have the release complete. Thanks.

**Comment by bolatovumar** [comment]
Alright, thanks.

**Comment by jkeyes** [comment]
:ship: 1.0 is now released: https://keyes.ie/things/baseliner/
