### ISSUE TITLE
HTTPS vs HTTP

### ISSUE THREAD

**Issue by glenpike** [jkeyes/baseline#7]
Suggest changing "http:" to "https:" in https://github.com/jkeyes/baseline/blob/master/baseliner/bookmarklet.src.js#L13

This prevents browsers blocking mixed content and the plugin failing silently.

Also think that the version of the bookmarklet here and in the [doc's](https://keyes.ie/things/baseliner/) differs - the one here "works" with the https fix, but there are errors when using the link similar to #6

**Comment by jkeyes** [comment]
@glenpike I changed to `https`. Thanks! (The bookmarklet is updated with a fix for #6 too.)
